"""change name in slabreached table agent_email -> api_email

Revision ID: 1400efba4831
Revises: 2f2a3a47f32d
Create Date: 2025-11-24 13:23:35.096730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1400efba4831'
down_revision: Union[str, Sequence[str], None] = '2f2a3a47f32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slabreached', sa.Column('api_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('slabreached', 'agent_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slabreached', sa.Column('agent_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('slabreached', 'api_email')
    # ### end Alembic commands ###
