"""create slabreached table

Revision ID: 2f2a3a47f32d
Revises: 67170c1f178d
Create Date: 2025-11-24 13:19:13.075279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f2a3a47f32d'
down_revision: Union[str, Sequence[str], None] = '67170c1f178d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slabreached',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('agent_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chat_breached', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slabreached')
    # ### end Alembic commands ###
