"""add out of adherence column

Revision ID: 41046f206d8d
Revises: b8ddc6c173a5
Create Date: 2025-10-20 12:25:00.710655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41046f206d8d'
down_revision: Union[str, Sequence[str], None] = 'b8ddc6c173a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
