"""baseline

Revision ID: 4716f96e132d
Revises: 
Create Date: 2025-10-13 12:05:11.743663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4716f96e132d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('forecast_tht', sa.Integer(), nullable=True),
    sa.Column('forecast_received', sa.Integer(), nullable=True),
    sa.Column('required_agents', sa.Integer(), nullable=True),
    sa.Column('scheduled_agents', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worktype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('manager', sa.String(length=60), nullable=True),
    sa.Column('supervisor', sa.String(length=60), nullable=True),
    sa.Column('coordinator', sa.String(length=60), nullable=True),
    sa.Column('work_type_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('contract_type_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.String(length=15), nullable=True),
    sa.Column('api_id', sa.String(length=40), nullable=True),
    sa.Column('api_name', sa.String(length=60), nullable=True),
    sa.Column('api_email', sa.String(length=60), nullable=True),
    sa.Column('observation_1', sa.String(length=60), nullable=True),
    sa.Column('observation_2', sa.String(length=60), nullable=True),
    sa.Column('tenure', sa.Integer(), nullable=True),
    sa.Column('trainee', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contracttype.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['work_type_id'], ['worktype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_email', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['api_email'], ['worker.api_email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_document', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('obs', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['worker_document'], ['worker.document'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubycallschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_document', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['worker_document'], ['worker.document'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubycallschedule')
    op.drop_table('schedule')
    op.drop_table('attendance')
    op.drop_table('worker')
    op.drop_table('worktype')
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('status')
    op.drop_table('role')
    op.drop_table('planned')
    op.drop_table('contracttype')
    op.drop_table('campaign')
    # ### end Alembic commands ###
