"""add real time data model

Revision ID: 6608c4460509
Revises: 242082bd96b3
Create Date: 2025-11-12 09:26:25.982864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6608c4460509'
down_revision: Union[str, Sequence[str], None] = '242082bd96b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realtimedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('contacts_received', sa.Integer(), nullable=True),
    sa.Column('sla_frt', sa.Float(), nullable=True),
    sa.Column('tht', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realtimedata')
    # ### end Alembic commands ###
