"""change columns in Schedule, add start_time, end_time remove date, day

Revision ID: b2baf26853ce
Revises: 551a87559306
Create Date: 2025-11-23 12:59:25.975223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2baf26853ce'
down_revision: Union[str, Sequence[str], None] = '551a87559306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('schedule', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('schedule', 'date')
    op.drop_column('schedule', 'day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('day', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('schedule', 'end_date')
    op.drop_column('schedule', 'start_date')
    # ### end Alembic commands ###
