"""init postgre schema

Revision ID: c5988743cc5c
Revises: 
Create Date: 2025-11-10 08:24:11.438902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5988743cc5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contracttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('forecast_tht', sa.Integer(), nullable=True),
    sa.Column('forecast_received', sa.Integer(), nullable=True),
    sa.Column('required_agents', sa.Integer(), nullable=True),
    sa.Column('scheduled_agents', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planneddata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('time_interval', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('forecast_received', sa.Integer(), nullable=True),
    sa.Column('forecast_aht', sa.Integer(), nullable=True),
    sa.Column('forecast_absenteeism', sa.Integer(), nullable=True),
    sa.Column('required_agents', sa.Integer(), nullable=True),
    sa.Column('scheduled_concentrix', sa.Integer(), nullable=True),
    sa.Column('scheduled_ubycalls', sa.Integer(), nullable=True),
    sa.Column('forecast_hours', sa.Float(), nullable=True),
    sa.Column('scheduled_hours', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('time_interval', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('real_received', sa.Integer(), nullable=False),
    sa.Column('real_attended', sa.Integer(), nullable=False),
    sa.Column('real_missed', sa.Integer(), nullable=False),
    sa.Column('real_abandoned', sa.Integer(), nullable=False),
    sa.Column('real_aht', sa.Integer(), nullable=False),
    sa.Column('real_sla_avr', sa.Float(), nullable=False),
    sa.Column('real_sla_frt', sa.Float(), nullable=False),
    sa.Column('sat', sa.Float(), nullable=False),
    sa.Column('qsat', sa.Integer(), nullable=False),
    sa.Column('sat_5', sa.Float(), nullable=False),
    sa.Column('real_concentrix', sa.Integer(), nullable=False),
    sa.Column('real_ubycalls', sa.Integer(), nullable=False),
    sa.Column('real_holding_time', sa.Integer(), nullable=False),
    sa.Column('real_acw_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worktype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('manager', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('supervisor', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('coordinator', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('work_type_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('contract_type_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('api_id', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('api_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('api_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('observation_1', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('observation_2', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tenure', sa.Integer(), nullable=True),
    sa.Column('trainee', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('productive', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contracttype.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['work_type_id'], ['worktype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_email'),
    sa.UniqueConstraint('document')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('out_of_adherence', sa.Integer(), nullable=True),
    sa.Column('offline_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_email'], ['worker.api_email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_document', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('obs', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.ForeignKeyConstraint(['worker_document'], ['worker.document'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubycallschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_document', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['worker_document'], ['worker.document'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubycallschedule')
    op.drop_table('schedule')
    op.drop_table('attendance')
    op.drop_table('worker')
    op.drop_table('worktype')
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('status')
    op.drop_table('role')
    op.drop_table('realdata')
    op.drop_table('planneddata')
    op.drop_table('planned')
    op.drop_table('contracttype')
    op.drop_table('campaign')
    # ### end Alembic commands ###
