"""add contacts_with_ccr new table

Revision ID: f05443c9990b
Revises: 740339d9072a
Create Date: 2025-12-18 00:42:21.588780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f05443c9990b'
down_revision: Union[str, Sequence[str], None] = '740339d9072a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactsreceived',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_pe', sa.Date(), nullable=True),
    sa.Column('interval_pe', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('date_es', sa.Date(), nullable=True),
    sa.Column('interval_es', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('contacts_received', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactsreceivedreason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contacts_received_id', sa.Integer(), nullable=False),
    sa.Column('contact_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contacts_received_id'], ['contactsreceived.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contactsreceivedreason')
    op.drop_table('contactsreceived')
    # ### end Alembic commands ###
