"""change length role.name

Revision ID: f2852c1c5f60
Revises: 035d569fe0d6
Create Date: 2026-01-08 13:11:06.006691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2852c1c5f60'
down_revision: Union[str, Sequence[str], None] = '035d569fe0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ux_contacts_received_dates_team'), table_name='contactsreceived')
    op.drop_index(op.f('ux_contacts_received_reason_parent_reason'), table_name='contactsreceivedreason')
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.create_index(op.f('ux_contacts_received_reason_parent_reason'), 'contactsreceivedreason', ['contacts_received_id', 'contact_reason'], unique=True)
    op.create_index(op.f('ux_contacts_received_dates_team'), 'contactsreceived', ['date_pe', 'interval_pe', 'date_es', 'interval_es', 'team'], unique=True)
    # ### end Alembic commands ###
