"""add unique constraint to name fields

Revision ID: fdcb161fbb79
Revises: 81bb2466ba28
Create Date: 2025-11-09 00:13:18.829003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdcb161fbb79'
down_revision: Union[str, Sequence[str], None] = '81bb2466ba28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'campaign', ['name'])
    op.create_unique_constraint(None, 'contracttype', ['name'])
    op.create_unique_constraint(None, 'role', ['name'])
    op.create_unique_constraint(None, 'status', ['name'])
    op.create_unique_constraint(None, 'team', ['name'])
    op.create_unique_constraint(None, 'worktype', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worktype', type_='unique')
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_constraint(None, 'status', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'contracttype', type_='unique')
    op.drop_constraint(None, 'campaign', type_='unique')
    # ### end Alembic commands ###
