"""add link column in sla_breached

Revision ID: ffc4102b0ff3
Revises: 1400efba4831
Create Date: 2025-11-25 09:36:50.519695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc4102b0ff3'
down_revision: Union[str, Sequence[str], None] = '1400efba4831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slabreached', sa.Column('link', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slabreached', 'link')
    # ### end Alembic commands ###
