TEAM = 'team'
DATE = 'date'
TIME_INTERVAL = 'time_interval'
FORECAST_RECEIVED = 'forecast_received'
FORECAST_AHT = 'forecast_aht'
FORECAST_ABSENTEEISM = 'forecast_absenteeism'
REQUIRED_AGENTS = 'required_agents'
SCHEDULED_AGENTS = 'scheduled_agents'
FORECAST_HOURS = 'forecast_hours'
SCHEDULED_HOURS = 'scheduled_hours'

SERVICE_LEVEL = 'service_level'
REAL_RECEIVED = 'real_received'

REAL_AGENTS = 'real_agents'
SAT_SAMPLES = 'sat_samples'
SAT_ONGOING = 'sat_ongoing'
SAT_PROMOTERS = 'sat_promoters'
SAT_INTERVAL = 'sat_interval'
