TEAM = 'team'
DATE = 'date'
TIME_INTERVAL = 'time_interval'
INTERVAL = 'interval'
FORECAST_RECEIVED = 'forecast_received'
FORECAST_THT = 'forecast_tht'
FORECAST_ABSENTEEISM = 'forecast_absenteeism'
REQUIRED_AGENTS = 'required_agents'
SCHEDULED_AGENTS = 'scheduled_agents'
FORECAST_HOURS = 'forecast_hours'
SCHEDULED_HOURS = 'scheduled_hours'

SERVICE_LEVEL = 'service_level'
REAL_RECEIVED = 'real_received'

SAT_SAMPLES = 'sat_samples'
SAT_ONGOING = 'sat_ongoing'
SAT_PROMOTERS = 'sat_promoters'
SAT_INTERVAL = 'sat_interval'
SAT_ABUSER = 'sat_abuser'
AHT = 'aht'

AGENTS_ONLINE = 'agents_online'
AGENTS_TRAINING = 'agents_training'
AGENTS_AUX = 'agents_aux'
